### ISSUE TITLE
Target allocation percentage bands

### ISSUE THREAD

**Issue by witten** [ghislainbourgeois/beancount_portfolio_allocation#4]
There are a variety of rebalancing techniques that rely on rebalance bands rather than a single target percentage. For instance, instead of rebalancing when something strays from its desired target of 40%, you might be more tolerant and only rebalance when it's outside a band of 32% to 48%. This can result in slightly higher returns. [Here's one such example.](https://www.onefpa.org/journal/pages/opportunistic%20rebalancing%20a%20new%20paradigm%20for%20wealth%20managers.aspx) (See PDF at the bottom.)

I've implemented such a feature in a fork, and the proposed docs for it are here, which gives an overview of the idea as it could exist in beancount_portfolio_allocation: https://github.com/witten/beancount_portfolio_allocation/tree/bands#target-bands

Before submitting a PR, I wanted to see if this sounds like something you might be amenable to. If so, I'll clean up the fork, get tests passing, and submit it.

**Comment by ghislainbourgeois** [comment]
Hi @witten, thanks for bringing this up, this looks really interesting!

I would definitely welcome a PR on this, I think this is an interesting feature. I looked at your new documentation and I am not quite sure how to fully use this yet, but we can discuss the specifics on the PR.

**Comment by witten** [comment]
I haven't had a chance to put together a PR, so please feel free to close the ticket if others aren't clamoring for this feature! Thanks.
